version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
      network: host
    ports:
      - "8050:8050"
    volumes:
      - ./llm_responses:/app/llm_responses
      - ./cache:/app/cache
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - OLLAMA_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: python app.py
    networks:
      - ai-dashboard-net

networks:
  ai-dashboard-net:
    driver: bridge