version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
      network: host
    ports:
      - "8050:8050"
    volumes:
      - ./llm_responses:/app/llm_responses
      - ./cache:/app/cache
    env_file:
      - ${ENV_FILE:-.env.default}
    environment:
      - OLLAMA_HOST=host.docker.internal
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy_key}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-dummy_key}
      - COHERE_API_KEY=${COHERE_API_KEY:-dummy_key}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: python app.py
    networks:
      - ai-dashboard-net

networks:
  ai-dashboard-net:
    driver: bridge

#networks:
 # default:
  #  driver: bridge
