services:
  ollama:
    build:
      context: .
      dockerfile: docker/Dockerfile.ollama
      network: host
    image: ollama_custom:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ai-dashboard-net

  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.dashboard
      network: host
    ports:
      - "8050:8050"
    volumes:
      - ./llm_responses:/app/llm_responses
      - ./cache:/app/cache
      - ./.env:/app/.env
      - ./.env.default:/app/.env.default
    environment:
      - OLLAMA_HOST=ollama
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy_key}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-dummy_key}
      - GROQ_API_KEY=${GROQ_API_KEY:-dummy_key}
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - ai-dashboard-net

networks:
  ai-dashboard-net:
    driver: bridge

volumes:
  ollama_data:
