version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./llm_responses:/app/llm_responses
      - ./cache:/app/cache
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
    networks:
      - app_network
  
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app_network

volumes:
  ollama_data:

networks:
  app_network:
    driver: bridge 