version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./llm_responses:/app/llm_responses
      - ./cache:/app/cache
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - OLLAMA_HOST=0.0.0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
    command: python app.py

networks:
  default:
    driver: bridge