services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    image: ollama_custom:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ai-dashboard-net

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8050:8050"
    volumes:
      - ./llm_responses:/app/llm_responses
      - ./cache:/app/cache
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - OLLAMA_HOST=ollama
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - ai-dashboard-net

networks:
  ai-dashboard-net:
    driver: bridge

volumes:
  ollama_data:
